spring:
  datasource:
    # Replace with your AWS RDS MySQL endpoint once deployed
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mana@community@8008
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'update' automatically creates/modifies tables to match your @Entity classes
      ddl-auto: create
      #ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: manacommunity
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false


server:
  port: 8080


# CORS Configuration for React Frontend
cors:
  allowed-origins: "http://localhost:3000"